# Use an official Java runtime as a parent image
FROM openjdk:21-jdk

# Set the working directory in the container to /app
WORKDIR /app

# Copy the executable JAR file from your host to the present location (.) in your image (i.e., /app)
COPY ../../code/Orchestra/Musician/target/Musician-1.0.jar /app/

# Run the JAR file when the container launches
ENTRYPOINT ["java", "-jar", "Musician-1.0.jar"]

# docker build -t dai/musician .\docker\image-musician\
# docker build -t dai/musician -f docker/image-musician/Dockerfile .
